# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npm run lint

  build:
    name: ${{ matrix.os }} with NodeJS ${{ matrix.node-version }} and NPM ${{ matrix.npm }}
    runs-on: ${{ matrix.os }}
    needs: lint

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        npm:
          - 7
          - 8

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm ${{ matrix.npm }}
      run: npm i -g npm@${{ matrix.npm }}
    - run: npm ci --ignore-scripts
    - run: npm test
